name: Restart Azure Web Apps

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  restart:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Restart MimiFront
        run: az webapp restart --name MimiFront --resource-group mnajerusRG

      - name: Restart MimiBack
        run: az webapp restart --name MimiBack --resource-group mnajerusRG
