name: Ping Mimi

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping MimiFront
        run: curl -I --max-time 30 https://mimifront-bjabgkefg2cmhh9.francecentral-01.azurewebsites.net || true

      - name: Ping MimiBack
        run: curl -I --max-time 30 https://mimiback-ghfxgefkahf3f5e9.francecentral-01.azurewebsites.net/ || true
